export default function Head() {
  return (
    <>
      <title>Olympus - CMS</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by Olympus - CMS" />
      <link rel="icon" href="/logo.ico" />
    </>
  )
}
